# Site
repository: rottenivy/rottenivy.github.io
favicon: images/favicon.ico
darkmode: false

# Personal info
name: Zhihao (Vincent) Zheng
title: Transportation Researcher
email: z.vincent.zheng@gmail.com
website: https://vincent-zheng.com/

# Social links
twitter_username: ZhihaoZheng95
googlescholar_username: h2Et54sAAAAJ
researchgate_username: Zhihao_Zheng4
# github_username:  rottenivy
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
google_analytics: "UA-141222335-1"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name's Zhihao and I am a masterâ€™s student with TransData Lab under Professor Pu Wang at Central South University since 2017. Prior to join TransData Lab, I completed my bachelorâ€™s degree in Transportation at Central South University, during which I visited The University of British Columbia and University of Oxford for short-term study. 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Publications Section
# publications_title: Selected Publications
publications_content : | # this will include new lines to allow paragraphs
   Zheng, Zhihao, et al. "Understanding coupling dynamics of public transportation networks." *EPJ Data Science* 7.1 (2018): 1-16. [[pdf](https://epjdatascience.springeropen.com/articles/10.1140/epjds/s13688-018-0148-6)]
   éƒ‘æ²»è±ª, et al. "åŸºäºç¤¾äº¤åª’ä½“å¤§æ•°æ®çš„äº¤é€šæ„ŸçŸ¥åˆ†æç³»ç»Ÿ." è‡ªåŠ¨åŒ–å­¦æŠ¥ 44.4 (2018): 656-666. [[pdf](http://html.rhhz.net/ZDHXBZWB/html/2018-4-656.htm)]

   <br>
   For a full list of my pubs, please check my [Google Scholar profile](https://scholar.google.com/citations?user=h2Et54sAAAAJ&hl=en).

# Blogs Section
# blogs_title : Blog Posts
blogs_content  : | # this will include new lines to allow paragraphs
  Pending

# Awards Section
# awards_title: Awards
awards_content : | # this will include new lines to allow paragraphs
   - Outstanding Graduate of Hunan Province (Postgraduate Student), 2020 <mark>1.9%</mark>
   - 2nd Prize, China Postgraduate Mathematical Contest in Modeling, 2019 <mark>13%</mark>
   - National Scholarship for Postgraduate Student, 2018 <mark>2%</mark>
   - Outstanding Postgraduate Student, 2018
   - Postgraduate Fellowship and 1st Class Scholarship, 2017
   - Outstanding Graduate of Hunan Province (Bachelor Student), 2017 <mark>2%</mark>
   - National Scholarship for Outstanding Students Majoring in Transportation Engineering, 2016 <mark>0.8%</mark>
   - 1st Prize, National Competition of Transport Science and Technology, 2016 <mark>2%</mark>
   - 1st Class Academic Scholarship, 2015
   - Xinheng Academic Scholarship, 2015
   - 2nd Class Academic Scholarship, 2014 & 2016
   - Outstanding Undergraduate Student, 2014 - 2016

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in research and innovation some of my other interests and hobbies are:
   
   âœˆï¸ Traveling: Canada, UK, Taiwan, Singapore, Hong Kong ...

   ğŸ“· Photography: check my Instagram! -> [@vzzheng](https://www.instagram.com/vzzheng/)

   ğŸ¹ Playing piano: just start it, lack of practicing -_-

   ğŸ® Gaming: Racing, FPS, FIFA (è½¦æªçƒï¼)

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme
remote_theme: rottenivy/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
